import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/header/Header";
import Footer from "@/components/layout/footer/Footer";
import QueryProvider from "@/context/QueryProvider";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Equarix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased font-inter content overflow-x-hidden flex flex-col`}
      >
        <QueryProvider>
          <Header />
          <main className="flex flex-col h-full overflow-x-hidden">
            {children}
          </main>
          <Footer />
        </QueryProvider>
      </body>
    </html>
  );
}
